// Equity lookups over the precomputed preflop table.
//
// The table is generated by scripts/buildEquityTable.mjs from this repo's own
// hand evaluator — nothing here is imported from a commercial solver or copied
// off a chart. That matters: it means every equity number the trainer shows can
// be traced to code you can read and re-run.

import { EQUITY_TABLE, EQUITY_STANDARD_ERROR } from '../data/equityTable';
import {
  CLASS_COUNT, classOfCards, comboCount, classNotation, classFromNotation,
} from './handClass';
import { parseCardIndex, rankOfCard, suitOfCard } from './handRank';

export { classNotation, classFromNotation, classOfCards };

/** Reported accuracy of the table, so callers can avoid over-stating it. */
export const EQUITY_TOLERANCE = EQUITY_STANDARD_ERROR;

/** Hand class for a two-card holding in the app's 'As' notation. */
export function classOfHand(hand) {
  return classOfCards(parseCardIndex(hand[0]), parseCardIndex(hand[1]));
}

/** Grid notation for a two-card holding: ['Ah','Kh'] -> 'AKs'. */
export function notationOfHand(hand) {
  return classNotation(classOfHand(hand));
}

/**
 * Equity of one hand class against another, as a fraction. Ties count as half.
 */
export function equityVsClass(heroClass, villainClass) {
  return EQUITY_TABLE[heroClass * CLASS_COUNT + villainClass] / 10000;
}

/**
 * Equity of a specific holding against a weighted range.
 *
 * Card removal is applied: holding the ace of spades leaves villain three aces,
 * so their AA drops from 6 combos to 3 and weighs proportionally less in the
 * average. Skipping this is a real error rather than a rounding one — it is
 * exactly the effect that makes blockers worth reasoning about.
 *
 * Known approximation: villain classes are weighted correctly, but the equity
 * used for each is the class average rather than one specific to hero's suits.
 * AhKh runs slightly differently against a heart-heavy range than AsKs does.
 * At chart granularity that difference is small, and it is the same
 * simplification every published range tool makes.
 *
 * @param hand two cards in 'As' notation
 * @param range Map|object of classIndex -> weight (0..1), or an array of indices
 * @returns {{equity: number, combos: number}} combos is villain's total
 *   remaining combinations, useful for showing how wide they actually are
 */
export function equityVsRange(hand, range) {
  const heroClass = classOfHand(hand);
  const heroCards = hand.map(parseCardIndex);
  const weights = normaliseRange(range);

  let weightedEquity = 0;
  let totalWeight = 0;
  let totalCombos = 0;

  for (const [villainClass, weight] of weights) {
    if (weight <= 0) continue;

    const combos = combosAvailable(villainClass, heroCards);
    if (combos <= 0) continue;

    const mass = weight * combos;
    weightedEquity += equityVsClass(heroClass, villainClass) * mass;
    totalWeight += mass;
    totalCombos += weight * combos;
  }

  return {
    equity: totalWeight > 0 ? weightedEquity / totalWeight : 0.5,
    combos: totalCombos,
  };
}

/**
 * How many combos of a class survive with some cards already dealt.
 * Counts concrete card pairs rather than applying a formula, so pairs, suited
 * and offsuit all fall out correctly without special cases.
 */
export function combosAvailable(classIndex, deadCards) {
  const dead = new Set(deadCards);
  let count = 0;

  for (const [c1, c2] of combosOfClass(classIndex)) {
    if (!dead.has(c1) && !dead.has(c2)) count++;
  }
  return count;
}

// Combos are enumerated once per class and cached — equityVsRange is called on
// every hand and a range can span a hundred classes.
const comboCache = new Map();
function combosOfClass(classIndex) {
  let combos = comboCache.get(classIndex);
  if (!combos) {
    combos = buildCombos(classIndex);
    comboCache.set(classIndex, combos);
  }
  return combos;
}

function buildCombos(classIndex) {
  const row = (classIndex / 13) | 0;
  const col = classIndex % 13;
  const rankHigh = 12 - Math.min(row, col);
  const rankLow = 12 - Math.max(row, col);
  const combos = [];

  if (row === col) {
    for (let s1 = 0; s1 < 4; s1++) {
      for (let s2 = s1 + 1; s2 < 4; s2++) combos.push([rankHigh * 4 + s1, rankHigh * 4 + s2]);
    }
  } else if (row < col) {
    for (let s = 0; s < 4; s++) combos.push([rankHigh * 4 + s, rankLow * 4 + s]);
  } else {
    for (let s1 = 0; s1 < 4; s1++) {
      for (let s2 = 0; s2 < 4; s2++) {
        if (s1 !== s2) combos.push([rankHigh * 4 + s1, rankLow * 4 + s2]);
      }
    }
  }
  return combos;
}

function normaliseRange(range) {
  if (range instanceof Map) return range;
  if (Array.isArray(range)) return new Map(range.map(c => [c, 1]));
  return new Map(Object.entries(range).map(([k, v]) => [Number(k), v]));
}

/** Total combos in a range, ignoring removal. A full range is 1326. */
export function rangeCombos(range) {
  let total = 0;
  for (const [classIndex, weight] of normaliseRange(range)) {
    total += weight * comboCount(classIndex);
  }
  return total;
}

/** A range's width as a percentage of all starting hands. */
export function rangePercent(range) {
  return rangeCombos(range) / 1326;
}

/**
 * Which of villain's holdings hero's cards block, and by how much.
 * Reported as combos removed, because "you block four of their sixteen AK
 * combos" is a usable thought and "you have a blocker" is not.
 */
export function blockerEffect(hand, villainClass) {
  const heroCards = hand.map(parseCardIndex);
  const before = comboCount(villainClass);
  const after = combosAvailable(villainClass, heroCards);
  return { before, after, removed: before - after };
}

/** Rank characters of a holding, for combinatorics helpers in odds.js. */
export function deadRanksOf(hand) {
  const RANKS = ['2', '3', '4', '5', '6', '7', '8', '9', 'T', 'J', 'Q', 'K', 'A'];
  return hand.map(c => RANKS[rankOfCard(parseCardIndex(c))]);
}

export { suitOfCard };
